# Generated by Django 5.1.1 on 2024-12-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_age',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='person',
            name='person_name',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
    ]
