# Generated by Django 5.1.1 on 2024-12-10 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_person_person_age_person_person_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Govind',
        ),
    ]
