# Generated by Django 5.1.1 on 2024-12-10 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_person_govind'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Govind',
            new_name='Person',
        ),
    ]
