# Generated by Django 5.1.1 on 2024-12-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_govind_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_address',
            field=models.TextField(default='No address available'),
        ),
    ]
