# Generated by Django 5.1.1 on 2024-12-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_person_person_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_address',
            field=models.TextField(null=True),
        ),
    ]
