# Generated by Django 5.1.1 on 2024-12-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_person_person_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.IntegerField(max_length=100)),
                ('Vehicle_num', models.IntegerField(max_length=4)),
            ],
        ),
    ]
