# Generated by Django 5.1.1 on 2024-12-11 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='Id',
            new_name='Sn',
        ),
    ]
